Added proxy into docker-in-docker config
eclipse-velocitas/devcontainer-base-images pull request #56
Opened 2023-10-26 11:57 UTC by kse3hi

This is neccesary to handle proxy with "base" images

2023-10-27 04:39 UTC, doosuu submitted a review, later dismissed

2023-10-27 04:39 UTC, doosuu commented on .devcontainer/scripts/configure-proxies.sh
> +        echo "File exist"
```suggestion
        echo "Existing docker config file found!"
```

2023-10-27 04:39 UTC, doosuu commented on .devcontainer/scripts/configure-proxies.sh
> +    mkdir -p /home/${USERNAME}/.docker
I suggest we introduce a variable for `/home/${USERNAME}/.docker` and re-use that also for `CONFIG_FILE`

2023-10-27 04:39 UTC, doosuu commented on .devcontainer/scripts/configure-proxies.sh
> +    echo $DOCKER_PROXY_JSON
Unnecessary echo

2023-11-01 14:11 UTC, dennismeister93 requested changes

2023-11-01 14:11 UTC, dennismeister93 commented on .devcontainer/scripts/configure-proxies.sh
> +    echo $DOCKER_CONFIG_FILE
is this echo necessary?

2023-11-02 09:16 UTC, kse3hi commented on .devcontainer/scripts/configure-proxies.sh
> +    echo $DOCKER_CONFIG_FILE
Looks like was added for debugging

2023-11-02 11:45 UTC, dennismeister93 approved these changes
lgtm

2023-11-02 12:27 UTC, merged

2023-11-02 13:21 UTC, kse3hi commented
https://github.com/eclipse-velocitas/vehicle-app-python-template/pull/213